import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import Loader from "../components/Loader";

import toast from "react-hot-toast";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>NextFire App</title>
				<meta name="NextFire App" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* <Loader show /> */}

			{/* <Link
				prefetch={false} //prop that Next will try to prefetch for performance
				href={{
					pathname: "/[username]",
					query: { username: "geov2" },
				}}
			>
				<a>Geo V2 Profile</a>
			</Link> */}

			<button onClick={() => toast.success("hello toast")}>Toast me!</button>
		</div>
	);
};

export default Home;
